[package]
name = "matrix"
version = "0.1.6"
authors = ["Igor Poloskov <ipoloskov@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.2.8"
